### PR TITLE
feat: Changed to use watch for wait rollout

### PR DESCRIPTION
**Pull request by stevehipwell**
This PR switches the logic for `wait_for_rollout` to use a watch and adds the missing functionality for `DaemonSet` & `StatefulSet` resources.

### CODE REVIEW

**Comment by stevehipwell** [comment]
@alekc could you take a look at this?

**Comment by alekc** [comment]
@stevehipwell could you rebase and fix conflicts please?

**Comment by stevehipwell** [comment]
@alekc I've rebased. I'm planning on doing the same changes for the `wait_for` block so would it be possible to hold the release until that's completed?

**Comment by alekc** [comment]
Sure, I'll wait for that one and make a 4.1.0-beta2 release (so that all changes can be tested entirely by using terraform registry  provider).

**Comment by stevehipwell** [comment]
@alekc could you give me a min, I've spotted a bug in the delete wait code which I'll fix in this PR.

**Comment by stevehipwell** [comment]
> @alekc could you give me a min, I've spotted a bug in the delete wait code which I'll fix in this PR.

Done

**Pull request merged**
