### PR TITLE
feat: Added support for user defined field manager

### PR DESCRIPTION
**Pull request by stevehipwell**
This PR enables the use of a user defined field manager to override the default `kubectl` one.

### CODE REVIEW

**Comment by alekc** [comment]
Thanks for the submission, looks good. 

Could you add test for this one? Cheers

**Comment by stevehipwell** [comment]
@alekc I'm not sure if it's possible with the current structure to add tests for something which only modifies the `managedFields` part of the resource as I don't think this is captured as part of the state.

**Comment by alekc** [comment]
Fair enough. I have a testing structure for live objects in a kubectl patch branch, I will reuse it and write test once its merged.

**Comment by stevehipwell** [comment]
@alekc it looks like the failing test is due to the existing setup logic and nothing to do with the code changes? Any thoughts?

**Comment by alekc** [comment]
yeah, it looks like there was some change in the github action setup. I will investigate it tomorrowish, and worst case scenario validate locally and force merge it.

**Pull request merged**
